steps:
- name: 'maven:3.6.1-jdk-8-slim'
  entrypoint: 'mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/src', '.']
images: ['gcr.io/$PROJECT_ID/source']
